version: "3.8"
services:
  app:
    image: tk1122/cloud-gaming
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    ports:
    - "8000:8000"
    restart: on-failure
    container_name: cloud-gaming