{{- if .Values.ingress.enabled -}}
  {{- $name := .Values.name -}}
  {{- $hostname := printf "%s.%s" .Values.name .Values.domain -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{$name}}-ingress
  {{- with .Values.ingress}}
  annotations:
  {{- .annotations | toYaml | nindent 4}}
spec:
  rules:
    - host: {{ $hostname | quote }}
      http:
        paths:
          - backend:
              serviceName: {{$name}}-service
              servicePort: http
  {{- end }}
  {{- end }}