apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-service
spec:
  {{- with .Values.service}}
  type: {{.type}}
  ports:
    - name: http
      port: {{.port}}
      targetPort: {{.targetPort}}
  {{- end}}